compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
num_processes: 2
mixed_precision: bf16
downcast_bf16: 'no'
rdzv_backend: static
same_network: true
main_training_function: main
use_cpu: false
gpu_ids: '0,1'
dynamo_backend: 'no'
fsdp_config: {}
deepspeed_config: {}
